const Data = [{redOnion: {id: 1,
                        name: 'Red onion',
                        img: '',
                        price: 0.99,
                        val: 0,
                        bill: 0}},
              {apple: {id: 2,
                        name: 'Apple',
                        img: '',
                        price: 2.19,
                        val: 0,
                        bill: 0}},
              {sweetMango: {id: 3,
                            name: 'Sweet Mango',
                            img: '',
                            price: 2.09,
                            val: 0,
                            bill: 0}},
              {pineapple: {id: 4,
                            name: 'Pineapple',
                            img: '',
                            price: 1.69,
                            val: 0,
                            bill: 0}}];
export default Data;